include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore
    invalid_annotation_target: ignore
    directives_ordering: ignore
    always_use_package_imports: ignore


  exclude:
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart  
    - lib/**.g.dart